grails-app/assets/javascripts/spApp/templates/menuContent.tpl.htm, grails-app/assets/javascripts/spApp/templates/sandBoxContent.tpl.htm, grails-app/assets/thirdparty/ala/ala-bootstrap3.js, grails-app/assets/thirdparty/ala/ala-styles.css, grails-app/conf/BuildConfig.groovy, grails-app/conf/Config.groovy, grails-app/views/layouts/main.gsp, grails-app/views/layouts/portal.gsp, grails-app/views/portal/index.gsp, package.json
Migrates the services that are currently available using HTTPS, while leaving the others as HTTP for now.
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>
=> issue #44 : Initial work to support HTTPS

grails-app/services/au/org/ala/spatial/portal/PropertiesService.groovy
Use of external resources packaged by:
https://github.com/living-atlases/ala-i18n
Other [similar PRs](https://github.com/search?q=is%3Apr+author%3Avjrj+org%3AAtlasOfLivingAustralia+ala-i18n+external&type=Issues).
=> Usage of external ala-i18n resources

grails-app/assets/javascripts/spApp/controller/toolCtrl.js, grails-app/assets/javascripts/spApp/directive/selectSpecies.js, grails-app/assets/javascripts/spApp/directive/speciesOptions.js, grails-app/assets/javascripts/spApp/service/toolExportChecklistService.js
=> #290 change area defaults

grails-app/assets/javascripts/spApp/service/biocacheService.js, grails-app/assets/javascripts/spApp/service/urlParamsService.js
=> 291 fix q with brackets

grails-app/assets/javascripts/spApp/service/biocacheService.js
=> #294 fix url param q

grails-app/assets/javascripts/spApp/directive/selectFacet.js, grails-app/assets/javascripts/spApp/service/biocacheService.js, grails-app/assets/javascripts/spApp/templates/selectFacetCtrl.tpl.htm
=> #293 Add all facets to Add to map | Facets

grails-app/assets/javascripts/spApp/controller/speciesInfoCtrl.js, grails-app/assets/javascripts/spApp/controller/toolCtrl.js, grails-app/assets/javascripts/spApp/directive/selectSpecies.js, grails-app/assets/javascripts/spApp/directive/speciesOptions.js, grails-app/assets/javascripts/spApp/service/biocacheService.js, grails-app/assets/javascripts/spApp/service/mapService.js, grails-app/assets/javascripts/spApp/service/predefinedAreasService.js, grails-app/assets/javascripts/spApp/service/toolAddFacetService.js, grails-app/assets/javascripts/spApp/service/toolExportChecklistService.js, grails-app/assets/javascripts/spApp/service/urlParamsService.js, grails-app/assets/javascripts/spApp/templates/selectSpeciesCtrl.tpl.htm, grails-app/assets/javascripts/spApp/templates/speciesInfoContent.tpl.htm, grails-app/assets/javascripts/spApp/templates/speciesOptionsContent.tpl.htm, grails-app/assets/javascripts/spApp/templates/toolContent.tpl.htm
=> Revise behaviour of species filters

grails-app/assets/javascripts/spApp/directive/pointComparison.js, grails-app/assets/javascripts/spApp/templates/pointComparisonContent.tpl.htm
=> #296 fix point comparison

grails-app/assets/javascripts/spApp/directive/selectArea.js, grails-app/assets/javascripts/spApp/service/biocacheService.js
=> #308 fix restricting species by area

grails-app/assets/javascripts/spApp/templates/selectLayersCtrl.tpl.htm
=> #304 remove redundant layer search box

_Events.groovy, grails-app/assets/javascripts/application.js, grails-app/assets/javascripts/spApp/controller/leafletMapController.js, grails-app/assets/stylesheets/application.css, grails-app/assets/stylesheets/spatial-hub.css, package.json
=> #286 add distance measure tool

grails-app/conf/application.yml
=> #284 match new search/grouped/facets

grails-app/assets/javascripts/spApp/controller/toolCtrl.js, grails-app/assets/javascripts/spApp/directive/selectArea.js, grails-app/assets/javascripts/spApp/templates/toolContent.tpl.htm
=> #292 fix tool init for lists

grails-app/assets/javascripts/spApp/controller/addWMSCtrl.js
=> #249 fix WMS proxy

grails-app/assets/javascripts/spApp/templates/selectSpeciesCtrl.tpl.htm
=> #319 return missing lifeform option to species selection

grails-app/assets/javascripts/spApp/controller/addAreaCtrl.js, grails-app/assets/javascripts/spApp/controller/createSpeciesListCtrl.js, grails-app/assets/javascripts/spApp/controller/sandBoxCtrl.js, grails-app/assets/javascripts/spApp/templates/addAreaContent.tpl.htm, grails-app/assets/javascripts/spApp/templates/createSpeciesListContent.tpl.htm, grails-app/assets/javascripts/spApp/templates/sandBoxContent.tpl.htm, grails-app/controllers/au/org/ala/spatial/portal/PortalController.groovy, grails-app/i18n/messages.properties, grails-app/views/portal/index.gsp
=> #285 Fix error messages on uploads

grails-app/conf/application.yml
Add OSM copyright to map attribution
=> add map copyright to config

grails-app/assets/javascripts/spApp/service/biocacheService.js, grails-app/assets/javascripts/spApp/service/urlParamsService.js
Loaded a stored session, will result complete map zoom out
https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/338
=> 338 map load zoom

grails-app/assets/javascripts/spApp/service/biocacheService.js, grails-app/services/au/org/ala/spatial/portal/SessionService.groovy
Fixed  missing urls after deleting a  session
=> 331 delete session

grails-app/assets/javascripts/spApp/controller/addAreaCtrl.js, grails-app/assets/javascripts/spApp/controller/areaReportCtrl.js, grails-app/assets/javascripts/spApp/directive/selectFacet.js, grails-app/assets/javascripts/spApp/service/sessionsService.js, grails-app/assets/javascripts/spApp/spApp.js, grails-app/controllers/au/org/ala/spatial/portal/PortalController.groovy, grails-app/i18n/messages.properties, grails-app/services/au/org/ala/spatial/portal/PortalService.groovy
=> 392 Capture error message from facets query

grails-app/controllers/au/org/ala/spatial/portal/LogController.groovy, grails-app/services/au/org/ala/spatial/portal/HubWebService.groovy
Original urlResponse did not pass params and headers into next http request. 
And also, it did not pass the default headers, e.g.  Accept to next level.
Not sure why?
This commit mainly fixes those issues
=> #390 fix(pass params/headers to all types of urlResponse )

build.gradle, grails-app/assets/javascripts/spApp/templates/createSpeciesListContent.tpl.htm, grails-app/controllers/au/org/ala/spatial/portal/PortalController.groovy, src/integration-test/groovy/AddSpeciesSpec.groovy, src/integration-test/groovy/page/AddSpeciesModule.groovy, src/integration-test/groovy/page/ModalModule.groovy
Fixing authentication issue when post species list to lists.ala.org.au
=> #416 fix(create a species list + tests)

grails-app/controllers/au/org/ala/spatial/portal/PortalController.groovy, src/integration-test/groovy/ToolPointsToGridSpec.groovy
Avoid to send a large set of features via queryString
=> #345 fix(post features via body)

grails-app/assets/javascripts/spApp/service/layoutService.js
=> Added id field to the area information

grails-app/assets/javascripts/spApp/controller/createSpeciesListCtrl.js, grails-app/assets/javascripts/spApp/service/bieService.js, grails-app/conf/application.yml, grails-app/views/portal/index.gsp
=> #470 use namematching-ws for some bie services

grails-app/assets/javascripts/spApp/directive/listsList.js, grails-app/assets/javascripts/spApp/service/facetAutoCompleteService.js, grails-app/assets/javascripts/spApp/service/listsService.js, grails-app/controllers/au/org/ala/spatial/portal/PortalController.groovy
For both species list issues #472 and #473
=> #472 #473 update species list queries

build.gradle, src/main/resources/META-INF/context.xml
=> #492 set lib load order
